DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS comments;

CREATE TABLE posts (
    id VARCHAR(200) PRIMARY KEY,
    title TEXT NOT NULL,
    link VARCHAR(2083)
);

CREATE TABLE comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user VARCHAR(20) NOT NULL,
    body TEXT NOT NULL,
    post VARCHAR(200) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(post) REFERENCES posts(id)
);

