DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS comments;

CREATE TABLE posts (
    id BLOB PRIMARY KEY,
    title TEXT NOT NULL
);

CREATE TABLE comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user VARCHAR(20) NOT NULL,
    body TEXT NOT NULL,
    post BLOB NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(post) REFERENCES posts(id)
);

